cookie:
  expiry_days: 30
  key: lolkek14881337cheburek
  name: greenea_cookie
credentials:
  usernames:
    Veronika:
      email: Veronika@greenea.com
      logged_in: false
      name: Nicole
      password: $2b$12$B6jUif07vIrAqifN9jIPnOv1Racm7Nv4XagkG1HyeXSmP6/3Ng71i
      telegram_id: 445376108
    tekkyon:
      email: deathskilled@gmail.com
      logged_in: false
      name: Vladimir
      password: $2b$12$VcZ0kbQ3XTEyP4vBLzOlduRfiaxHC3Q5P8ujUyXzbMBy/Rn0.TXJ6
      telegram_id: 784570394
    "\u0421\u0442\u0435\u043F\u0430\u043D":
      email: "\u0421\u0442\u0435\u043F\u0430\u043D@greenea.com"
      logged_in: false
      name: Stepan
      password: $2b$12$XXu0aSOTus3YhTa4Gzk75e/XSKDNA5YygBdEkOiBCkP7Fupu/A1ni
      telegram_id: 1356911800
    "\u0433\u0430\u0431\u0430\u0440\u0438\u0442\u044B":
      email: "\u0433\u0430\u0431\u0430\u0440\u0438\u0442\u044B@greenea.com"
      logged_in: false
      name: Vladimir
      password: $2b$12$QWP2nb1VDnd5uCdMJetLneZZfRkwYoPBn.Ci8PKpkMr5v.JmwfE.O
      telegram_id: 784570394
preauthorized:
  emails:
  - deathskilled@gmail.com
