cookie:
  expiry_days: 30
  key: lolkek14881337cheburek
  name: greenea_cookie
credentials:
  usernames:
    Veronika:
      email: Veronika@greenea.com
      logged_in: false
      name: Nicole
      password: $2b$12$B6jUif07vIrAqifN9jIPnOv1Racm7Nv4XagkG1HyeXSmP6/3Ng71i
      telegram_id: 445376108
    frolov:
      email: frolov@greenea.com
      logged_in: false
      name: "\u0410\u043B\u0435\u043A\u0441\u0430\u043D\u0434\u0440"
      password: $2b$12$siqep3Sy38XQHgttTIOk4e77TPtB3XDe5jJgFI7VXlIKnL8.Zogte
      telegram_id: 667267570
    tekkyon:
      email: deathskilled@gmail.com
      logged_in: false
      name: Vladimir
      password: $2b$12$VcZ0kbQ3XTEyP4vBLzOlduRfiaxHC3Q5P8ujUyXzbMBy/Rn0.TXJ6
      telegram_id: 784570394
    "\u0416\u043C\u044B\u0445":
      email: "\u0416\u043C\u044B\u0445@greenea.com"
      logged_in: false
      name: Vladimir
      password: $2b$12$PgL78FoD/4QeYYUaG7o7V.auJZ6zNlZS3D3YusrFBfwG9RbmfLwYe
      telegram_id: 784570394
    "\u0421\u0442\u0435\u043F\u0430\u043D":
      email: "\u0421\u0442\u0435\u043F\u0430\u043D@greenea.com"
      logged_in: false
      name: Stepan
      password: $2b$12$XXu0aSOTus3YhTa4Gzk75e/XSKDNA5YygBdEkOiBCkP7Fupu/A1ni
      telegram_id: 1356911800
preauthorized:
  emails:
  - deathskilled@gmail.com
