month_dict = {'January-': 'Январь',
              'February-': 'Февраль',
              'March-': 'Март',
              'April-': 'Апрель',
              'June-': 'Июнь',
              'May-': 'Май',
              'July-': 'Июль',
              'August-': 'Август',
              'September-': 'Сентябрь',
              'October-': 'Октябрь',
              'November-': 'Ноябрь',
              'December-': 'Декабрь', }

lexicon_dict = {'bad_package': 'Проблема со сборкой',
                'defect': 'Проблема с товаром',
                'wb': 'Wildberries',
                'ozon': 'Озон',
                'ym': 'Яндекс.Маркет',
                'sber': 'Сбер',
                'b2b': 'B2B'}