cookie:
  expiry_days: 30
  key: lolkek14881337cheburek
  name: greenea_cookie
credentials:
  usernames:
    Veronika:
      email: Veronika@greenea.com
      logged_in: false
      name: Nicole
      password: $2b$12$B6jUif07vIrAqifN9jIPnOv1Racm7Nv4XagkG1HyeXSmP6/3Ng71i
      telegram_id: 445376108
    tekkyon:
      email: deathskilled@gmail.com
      logged_in: false
      name: Vladimir
      password: $2b$12$VcZ0kbQ3XTEyP4vBLzOlduRfiaxHC3Q5P8ujUyXzbMBy/Rn0.TXJ6
      telegram_id: 784570394
preauthorized:
  emails:
  - deathskilled@gmail.com
